### ISSUE TITLE
error after using masterball inside discord-pokesniper 1.4.1

### ISSUE THREAD

**Issue by jeffreydeleeuw** [RebliNk17/Discord-PokeSniper#4]
after masterball has started loot pokestops at the end i get this msg:

[18:36:15] Another Pokestop was robbed, total robbed: 77
[18:36:25] Another Pokestop was robbed, total robbed: 78
[18:36:27] Another Pokestop was robbed, total robbed: 79
java.lang.NumberFormatException: For input string: "224,41"
        at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
        at sun.misc.FloatingDecimal.parseDouble(Unknown Source)
        at java.lang.Double.parseDouble(Unknown Source)
        at resources.SyncPipe.analyzeString(SyncPipe.java:86)
        at resources.SyncPipe.run(SyncPipe.java:31)
        at java.lang.Thread.run(Unknown Source)

**Comment by RebliNk17** [comment]
are you sure it's 1.4.1?
it should works fine.
Ill give it another look

**Comment by jeffreydeleeuw** [comment]
hmmm 1.4.0 sorry
updated now, lets see when i run out of pokeballs
